#' Aggregate decrypted instances into a dataframe
#'
#' @param instanceRegistry Instance registry dataframe generated by decryptInstances
#' @param formInfo Form info file generated by setupFormDirectory
#' @param oldData Optional, dataframe with existing data to be merged with new instances
#'
#' @return Dataframe of aggregated, decrypted instances
#' @importFrom stringr str_replace
#' @importFrom utils read.csv
#' @importFrom rlang .data
#' @import dplyr
#' @export
#'
#' @examples
aggregateInstances <- function(instanceRegistry, formInfo, oldData = NULL) {

  dt <- data.frame()
  instanceFilePaths <- instanceRegistry$decrypted_file_path

  if(!is.null(oldData)) {
    instanceFilePaths <- instanceRegistry[which(!instanceRegistry$uuid %in% oldData$instanceID),]$decrypted_file_path
  }

  if (length(instanceFilePaths) > 0) {
    # Agrégation des instances
    dt <- mergeInstanceData(instanceFilePaths, formInfo$repeatedNodePaths)

    # Vérification de l'adéquation au schéma
    mold <- read.csv(formInfo$csvMoldFilePath)
    if(checkDataStructure(dt, mold)){

      # Moulage des données dans le schéma
      baseDt <- data.frame(t(rep("", nrow(mold))))
      names(baseDt) <- mold$path
      baseDt <- baseDt[-1,]
      dt <- bind_rows(baseDt,dt)
      names(dt) <- mold$name

      if(!is.null(oldData)){
        if(checkDataStructure(oldData, mold)){
          dt <- bind_rows(oldData, dt)
        }
        else{
          warning("Old data do not match the mold")
        }
      }

      dt <- dt %>% arrange(.data$start)
    }
    else{
      warning("Decrypted data do not match the mold")
    }
  }

  return(dt)
}
