#' Decrypt encrypted instance files
#'
#' @param instanceRegistry Instance registry dataframe generated by getEncryptedInstances
#' @param privateRSAKey Private RSA key (base64 encoded)
#' @param writeToPath Path to directory where to save decrypted instance files
#'
#' @return Instance registry dataframe with paths to individual decrypted instances files
#' @importFrom stringr str_detect
#' @export
#'
#' @examples
decryptInstances <- function(instanceRegistry, privateRSAKey, writeToPath) {

  if(dir.exists(writeToPath)){
    instanceRegistry$decrypted_file_path <- NA_character_
    imax <- nrow(instanceRegistry)
    for(i in 1:imax){
      uuid <- instanceRegistry[i,]$uuid

      messageLead <- paste0(sprintf(paste0("%0",nchar(imax),"d"), i), "/", imax)

      if(!is.na(uuid)){
        encFilePath <- instanceRegistry[i,]$encrypted_file_path
        if(file.exists(encFilePath)){
          instanceId <- paste0("uuid:", uuid)
          instanceKey <- instanceRegistry[i,]$base64EncryptedKey

          xml <- decryptInstanceFile(encFilePath, instanceId, instanceKey, privateRSAKey)
          if(str_detect(xml, "^<\\?xml")){
            decFilePath <- paste0(writeToPath, uuid, ".xml")
            write(xml, decFilePath)
            if(file.exists(decFilePath)){
              message(paste0(messageLead, " - ", uuid, " instance file decryption success"))
              instanceRegistry[i,]$decrypted_file_path <- decFilePath
            }
          }
          else{
            message(paste0(messageLead, " - ", uuid, " instance file decryption failure"))
          }
        }
        else {
          message(paste0(messageLead, " - ", uuid, " encrypted instance file not found"))
        }
      }
    }
  }
  else {
    warning("The specified directory does not exist.")
  }

  return(instanceRegistry)
}

